name: 07-contexts
on:
    push: 
    workflow_dispatch: 

jobs:
    echo-data:
        runs-on: ubuntu-latest
        steps:
            - name: showinfo
              run: |
               echo "Nombre del evento: ${{github.event_name}}"
               echo "Ref: ${{github.ref}}"
               echo "SHA: ${{github.sha}}""
               echo "Actor: ${{github.actor}}""
               echo "Flujo de trabajo: ${{github.job_workflow_sha}}""
               echo "ID de ejecución: ${{github.run_id}}""
               echo "Número de ejecución: ${{github.run_number}}""
            - name: Retrive Variable
              run: echo ${{vars.MY_VAR}}
    
