name: 08 - Expressions
run-name: 08 - Expressions | DEBUG - < ${{ inputs.debug && 'ON' || 'OFF' }}>
on: 
    workflow_dispatch: 
        inputs:
            debug:
                description: 'Debug mode'
                required: true
                type: boolean
                default: false
jobs:
    echo:
        runs-on: ubuntu-latest
        steps:
            - name: ${{inputs.debug}} Print start-up
              if: inputs.debug == true
              run: |
                 echo "Triggered by: ${{ github.event_name}}"
                 echo "Branch: ${{ github.ref}}"
                 echo "Commit SHA: ${{ github.sha}}"
                 echo "Runner OS: $RUNNER_OS"
            - name: ${{inputs.debug}} Print when triggered from main
              if: inputs.debug == true && github.ref == 'refs/heads/main'
              run: |
                    echo "I was triggered from main"
            - name: Greeting            
              run: |
                    echo "Hello world"              