name: 10 - Using Functions
on:
    pull_request:        
    Workflow_dispatch:      
jobs:
    echo1: 
        runs-on: ubuntu-latest
        steps:
            - name: Failling step
              run: |
                exit 1
            
            - name: I will be skipped
              if: success()
              run: |
                  echo "I will print if previous step succeeds"
            
            - name: I will execute
              if: failure()
              run: |
                    echo "I will print if any previous step fails"

            - name: I will execute 2
              if: ${{ !cancelled() }}
              run: |
                    echo "I will always print, except when the workflow is cancelled"
              
            - name: I will execute when cancelled
              if: cancelled()
              run: |
                    echo "I will always print, even when the workflow is cancelled"            
            
            - name: Print PR title
              run: |
                    echo "PR title: ${{ github.event.pull_request.title }}"
                  
            - name: Print PR labels
              run: |
                 cat << EOF
                 ${{ toJSON(github.event.pull_request.labels) }}
                 EOF
                  
            - name: Bug step
              if: ${{ !cancelled() && contains(github.event.pull_request.title, 'fix') }}
              run: |
                   echo "I am a bug fix"
            
            - name: Sleep for 20 seconds
              run: |
                   sleep 20           
            