name: 11 - Controlling the Execution Flow
on: 
  workflow_dispatch:
    inputs:
      pass-unit-tests:
        description: 'Run unit tests'        
        type: boolean
        default: false
jobs:    
    lint-build:
        runs-on: ubuntu-latest
        steps:      
        - run: |
            echo "BLinting and building project"
    unit-tests:
        runs-on: ubuntu-latest
        continue-on-error: true
        steps:      
            - name: Run unit tests
              run: |
                echo "Running unit tests..."
            - name: Failling unit tests
              if: ${{ !inputs.pass-unit-tests }}
              run: |
                exit 1                
    deploy-non-prod:
        runs-on: ubuntu-latest
        needs: 
            - lint-build
            - unit-tests
        steps:      
            - name: Deploy to non-prod environment
              run: |
                echo "Deploying to non-prod environment"
    e2e-tests:
        runs-on: ubuntu-latest
        needs: 
            - deploy-non-prod
        steps:      
            - name: Run end-to-end tests
              run: |
                echo "Running end-to-end tests..."
    load-tests:
        runs-on: ubuntu-latest
        needs: 
            - deploy-non-prod
        steps:      
            - name: Run load tests
              run: |
                echo "Running load tests..."
    deploy-prod:
        runs-on: ubuntu-latest
        needs: 
            - e2e-tests
            - load-tests
        steps:      
            - name: Deploy to prod environment
              run: |
                echo "Deploying to prod environment"