name: 13 - Working with Outputs
on: 
    workflow_dispatch:
        inputs:
            build_status:
                description: 'Choose the build status for the demo'
                type: choice
                options:
                    - success
                    - failure
                default: success
jobs:
    build:
        runs-on: ubuntu-latest
        outputs:
            build_status: ${{ steps.build.outputs.status }}
        steps:      
            - name: 'Print GITHUB_OUTPUT path'       
              run: |
                echo "var -->> $GITHUB_OUTPUT"
            - name: Build
              id: build
              run: |
                echo "Building"
                echo "status=${{inputs.build_status}}" >> "$GITHUB_OUTPUT"

    deploy:
        runs-on: ubuntu-latest
        if: ${{ needs.build.outputs.build_status == 'success' }}
        needs: 
            - build
        steps:      
            - name: Deploy                                     
              run: |
                echo "Deploying"