name: 14 - Using Cache
on: 
    workflow_dispatch:
        inputs:
            use-cache:
                description: 'Use cache to speed up the workflow'        
                type: boolean
                default: true
            node-version:
                description: 'Node version to use'        
                type: choice
                options:
                    - '18.x'
                    - '20.x'
                    - '21.x'
                default: '20.x'
jobs:
    build:
        needs: install-deps
        runs-on: ubuntu-latest
        defaults:
            run:
                working-directory: 14-caching/react-app
        steps:      
            - name: Checkout
              uses: actions/checkout@v2
            - name: Setup Node
              uses: actions/setup-node@v2
              with:
                  node-version: '${{inputs.node-version}}'

            - name: Download cached dependencies
              id: cache              
              uses: actions/cache@v3
              with:
                key: ${{ needs.install-deps.outputs.deps-cache-key }}
                path: 14-caching/react-app/node_modules   
           
            - name: Testing
              run: |
                npm run test            
        
            - name: Building
              run: |
                npm run build
            
            - name: Deploy to nonProd              
              run: |
                echo "Deploying to nonProd"
            
    install-deps:
        outputs:
            deps-cache-key: ${{ steps.cache-key.outputs.CACHE_KEY }}
        runs-on: ubuntu-latest
        defaults:
            run:
                working-directory: 14-caching/react-app
        steps:      
            - name: Checkout
              uses: actions/checkout@v2
            - name: Setup Node
              uses: actions/setup-node@v2
              with:
                  node-version: '${{inputs.node-version}}'
            - name: Calculate cache key
              id: cache-key
              run: echo  "CACHE_KEY=deps-node-modules-${{ hashFiles('14-caching/react-app/package-lock.json') }} " >> "$GITHUB_OUTPUT"
              
            - name: Download cached dependencies
              id: cache              
              uses: actions/cache@v3
              with:
                key: ${{ steps.cache-key.outputs.CACHE_KEY }}
                path: 14-caching/react-app/node_modules  
        
            - name: install dependencies
              if: steps.cache.outputs.cache-hit != 'true'
              run: |
                 npm ci
    linting: 
        runs-on: ubuntu-latest
        needs: install-deps
        defaults:
            run:
                working-directory: 14-caching/react-app
        steps:      
            - name: Checkout
              uses: actions/checkout@v2
            - name: Setup Node
              uses: actions/setup-node@v2
              with:
                  node-version: '${{inputs.node-version}}'
            - name: Download cached dependencies
              id: cache            
              uses: actions/cache@v3
              if: ${{ needs.install-deps.outputs.deps-cache-key != '' }}
              with:
                key: ${{ needs.install-deps.outputs.deps-cache-key }}
                path: 14-caching/react-app/node_modules  
            - name: Testing
              run: |
                npm run test  
            - name: Linting
              run: |
                echo "Linting..."