name: 15 - Working with Artifacts
on: 
    workflow_dispatch:     
env:
    build-artifact-key: app-${{ github.sha }}
    test-coverage-key: test-coverage-${{ github.sha }}
jobs:
    test-build:
        runs-on: ubuntu-latest
        defaults:
            run:
                working-directory: 15-artifacts/react-app
        steps:      
            - name: Checkout
              uses: actions/checkout@v2
            - name: Setup Node
              uses: actions/setup-node@v2
              with:
                  node-version: '20.x'
            - name: Download cached dependencies
              id: cache            
              uses: actions/cache@v3              
              with:
                key: deps-node-modules-${{ hashFiles('15-artifacts/react-app/package-lock.json') }}
                path: 15-artifacts/react-app/node_modules

            - name: install dependencies
              if: steps.cache.outputs.cache-hit != 'true'
              run: |
                  npm ci

            - name: Testing
              run: |
                npm run test -- --coverage

            - name: Upload test results
              uses: actions/upload-artifact@v4
              with:
                  name: ${{ env.test-coverage-key }}
                  path: 15-artifacts/react-app/coverage                  
                  
            - name: Build code
              run: |
                npm run build

            - name: Upload build files
              uses: actions/upload-artifact@v4
              with:
                  name: ${{ env.build-artifact-key }}
                  path: 15-artifacts/react-app/build
    deploy:
        runs-on: ubuntu-latest
        needs: 
            - test-build
        steps:         
            - name: Download build files
              uses: actions/download-artifact@v4
              with:
                  name: ${{ env.build-artifact-key }}
                  path: build      